# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Original URL')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('click_count', models.IntegerField(default=0, verbose_name='Click Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
            ],
        ),
    ]
