# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='expired_in',
            field=models.PositiveIntegerField(choices=[(1, 'One Day'), (2, 'One Week'), (3, 'One Month'), (4, 'One Year')], default=1, verbose_name='Expired In'),
            preserve_default=False,
        ),
    ]
